# run test only
# docker-compose run --rm autobdd-test-run "xvfb-runner.sh make test-all"
#
# test development
# docker-compose up -d autobdd-test-dev
# docker-compose logs -f autobdd-test-dev
# ssh -o StrictHostKeyChecking=no $USER@localhost -p 2224
# default password is "ubuntu"
# in container ssh: make test-all
# vnc localhost:5924
# docker-compose down
# 
version: '3.5'
services:

  # dev container for developing autobdd test
  autobdd-test-dev:
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd-test-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/${ProjectsBase:-Projects}/${BDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}:delegated
    ports:
      - "5924:5900"
      - "2224:22"
      - "8004:8000"
    environment:
      - USER=${USER}
      - BDD_PROJECT=${BDD_PROJECT}
      - HOSTOS=${HOSTOS}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - PASSWORD=${PASSWORD}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - RESOLUTION=1920x1200x24
    entrypoint: "/root/autobdd-dev.startup.sh"

  # run container for running autobdd test
  autobdd-test-run:
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd-test-run
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/${ProjectsBase:-Projects}/${BDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${BDD_PROJECT}:delegated
    environment:
      - USER=${USER}
      - BDD_PROJECT=${BDD_PROJECT}
      - HOSTOS=${HOSTOS}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
    entrypoint: "/root/autobdd-run.startup.sh"
